networks:
  popplay:

services:
  DB:
    image: postgres:13.16-bookworm
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=DB_PopPlay
    ports:
      - "5432:5432"
    networks:
      - popplay
    secrets:
       - db_password

  back:
    build: PopPlay
    depends_on:
      - DB
    environment:
      - DB_HOST=DB
    networks:
      - popplay

  front:
    build: PopPlay_Angular
    networks:
      - popplay

  # cf: proxy/nginx.conf 
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - popplay
    depends_on:
      - back
      - front

secrets:
  db_password:
    file: secrets/DB_PWD.txt
  # cf_id:
  #   file: secrets/CF_ID.txt
  # cf_acc_key:
  #   file: secrets/CF_ACC_KEY.txt
  # cf_sec_key:
  #   file: secrets/CF_SEC_KEY.txt